### ISSUE TITLE
Build fails because of missing `mkpath` sub

### ISSUE THREAD

**Issue by lizmat** [zostay/DateTime-DST#6]
Not sure where that would have been coming from: but trying to install it with `zef` results in:

    $ zef install .
    ===> Building: DateTime::DST:ver<0.2>:auth<github:zostay>
    ===SORRY!=== Error while compiling /Users/liz/Github/DateTime-DST/Build.pm
    Undeclared routine:
        mkpath used at line 8

**Comment by AlexDaniel** [comment]
If `mkpath` is changed to `mkdir`, it then fails on the next line with `make`.

I tried to fix that by doing ```make($dist-path, ~$resources-dir);```, now it fails with:
```
Cannot locate native library '/home/alex/git/resources/libdsthelper.so': /home/alex/git/resources/libdsthelper.so: cannot open shared object file: No such file or directory
```

**Comment by zostay** [comment]
I've updated the build system to use the latest LibraryMake boilerplate and it's better, but it's still a little off. (Also filed retupmoca/P6-LibraryMake#25 because there's at least one error in the current boilerplate.)

**Comment by zostay** [comment]
I believe the build failures have been resolved.

**Comment by JJ** [comment]
> I've updated the build system to use the latest LibraryMake boilerplate and it's better, but it's still a little off. (Also filed [retupmoca/P6-LibraryMake#25](https://github.com/retupmoca/P6-LibraryMake/issues/25) because there's at least one error in the current boilerplate.)

Can you please point precisely to the error? A PR would also be extremely helpful.
